<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="9677" started-at="2019-08-13T19:15:05Z" finished-at="2019-08-13T19:15:15Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="9677" started-at="2019-08-13T19:15:05Z" finished-at="2019-08-13T19:15:15Z">
      <class name="com.testcases.DemoTest">
        <test-method status="PASS" signature="setUpSuite()[pri:0, instance:com.testcases.DemoTest@66d33a]" name="setUpSuite" is-config="true" duration-ms="749" started-at="2019-08-14T00:45:05Z" finished-at="2019-08-14T00:45:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpSuite -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.testcases.DemoTest@66d33a]" name="setUp" is-config="true" duration-ms="7931" started-at="2019-08-14T00:45:05Z" finished-at="2019-08-14T00:45:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="reportInitialize(java.lang.reflect.Method)[pri:0, instance:com.testcases.DemoTest@66d33a]" name="reportInitialize" is-config="true" duration-ms="140" started-at="2019-08-14T00:45:13Z" finished-at="2019-08-14T00:45:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.testcases.DemoTest.demoTest() throws java.lang.InterruptedException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportInitialize -->
        <test-method status="FAIL" signature="demoTest()[pri:0, instance:com.testcases.DemoTest@66d33a]" name="demoTest" duration-ms="58" started-at="2019-08-14T00:45:13Z" finished-at="2019-08-14T00:45:13Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.utilities.ExcelDataProvider.getData(ExcelDataProvider.java:36)
	at com.testcases.DemoTest.demoTest(DemoTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoTest -->
        <test-method status="PASS" signature="tearDownMethod(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:com.testcases.DemoTest@66d33a]" name="tearDownMethod" is-config="true" duration-ms="819" started-at="2019-08-14T00:45:13Z" finished-at="2019-08-14T00:45:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=demoTest status=FAILURE method=DemoTest.demoTest()[pri:0, instance:com.testcases.DemoTest@66d33a] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.testcases.DemoTest.demoTest() throws java.lang.InterruptedException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownMethod -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.testcases.DemoTest@66d33a]" name="tearDown" is-config="true" duration-ms="705" started-at="2019-08-14T00:45:14Z" finished-at="2019-08-14T00:45:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.testcases.DemoTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
